{% set name = "r-essentials" %}
{% set version = "3.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  # r-rbokeh is not available under Windows
  skip: true  # [win]
  number: 0

requirements:
    run:
        - r-base
        - r-recommended >={{ version }}
        - r-ggplot2 >=2.2.1
        - r-plyr >=1.8.4
        - r-reshape2 >=1.4.2
        - r-dplyr >=0.7.4
        - r-tidyr >=0.7.1
        - r-caret >=6.0_76
        - r-randomforest >=4.6_12
        - r-data.table >=1.10.4
        - r-quantmod >=0.4_8
        - r-shiny >=1.0.5
        - r-rmarkdown >=1.6
        - r-glmnet >=2.0_5
        - r-jsonlite >=1.5
        - r-zoo >=1.7_14
        - r-irkernel >=0.8.11
        - r-rbokeh >=0.5.0
        - r-formatr >=1.4
        - notebook >=5.4.0
        - r-tidyverse >=1.1.1
        - r-dbi >=0.6_1
        - r-broom >=0.4.2
        - r-forcats >=0.2.0
        - r-haven >=1.0.0
        - r-hms >=0.3
        - r-httr >=1.2.1
        - r-lubridate >=1.6.0
        - r-magrittr >=1.5
        - r-modelr >=0.1.0
        - r-purrr >=0.2.3
        - r-readr >=1.1.1
        - r-readxl >=1.0.0
        - r-rvest >=0.3.2
        - r-stringr >=1.2.0
        - r-tibble >=1.4.2
        - r-xml2 >=1.1.1

test:
  commands:
    - $R -e "library('ggplot2')"  # [not win]
    - $R -e "library('tibble')"  # [not win]
    - "\"%R%\" -e \"library('ggplot2')\""  # [win]
    - "\"%R%\" -e \"library('tibble')\""  # [win]

about:
    home: https://github.com/conda-forge/r-essentials-feedstock
    license: Various
    license_family: Other
    summary: Some essential packages for working with R. This was migrated from the 'r' channel.

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
